[client]
showSidebarNavigation = false

[theme]
primaryColor = "#1a6a9a"
backgroundColor = "#f0f8ff"
secondaryBackgroundColor = "#e6f2fa"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
